### PR TITLE
SCSS: Don't step on .dropdown-menu global namespace

### PR DESCRIPTION
**Pull request by OdyX**
Given .dropdown-menu is used in plenty other places in Moodle, the CSS in `mod_turnitintooltwo` will step on Moodle's global CSS namespace. It will enforce a 2px margin on all Dropdowns accross Moodle.

These commits are not perfect but they at least namespace the dropdown-menu styles somewhat.

### CODE REVIEW

**Comment by rlorenzo** [comment]
We ran into this same issue on our system. +1 on this patch.

**Comment by dwinn** [comment]
Hi @OdyX,

Thanks for the pull request. We will look at changing this as I agree we shouldn't be overriding Moodle styles. There are merge conflicts with your pull request however.

**Comment by OdyX** [comment]
The conflicts are in the _compiled_ files; just cherry-pick the https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/414/commits/96d32d238947707c13978c0adc1c078c02905468 commit and recompile :-)

**Comment by OdyX** [comment]
Rebased, and targetted master.

**Comment by rlorenzo** [comment]
@OdyX I believe @dwinn wants use to submit patches based off od develop branch, not master. See https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/452#issuecomment-421949703

**Comment by dwinn** [comment]
Yeah that's correct @rlorenzo, we need the patch to be based off of develop.

**Comment by jmcgettrick** [comment]
Thanks for the PR. Due to the conflicts in styles.css and styles.css.map I'll commit this manually.

**Comment by rlorenzo** [comment]
Although this pull request was closed, the fix was not implemented. In v2019050101 the . dropdown-menu style is still in the global namespace. See https://github.com/turnitin/moodle-mod_turnitintooltwo/blob/06523a923a37466717008964d3ad56ead7d8d76f/sass/partials/_inbox.scss#L86

**Pull request closed without merging**
