### PR TITLE
Submission inbox list inactive students

### PR DESCRIPTION
**Pull request by junwan6**
- fix to exclude inactive students without submission in submission inbox and as a result, inactive students with submission are marked as "Non Enroled student"
- fix to exclude inactive students when click "Enrol All Students"

### CODE REVIEW

**Comment by jmcgettrick** [comment]
Hi @junwan6 - could you resubmit this pull request please, to the develop branch. Thanks!

**Comment by jmcgettrick** [comment]
Closing, superseded by https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/183

**Comment by junwan6** [comment]
Hi John,

I have some suggestion on Turnitintooltwo Moodle module.  Can you please let me know the email address that I can reach at?

Thank you

Jun

**Comment by cwestgarth** [comment]
Hi @junwan6 , 

Please contact integrations@turnitin.com.

Kind Regards

Caroline Westgarth

**Pull request closed without merging**
