### PR TITLE
Issue #569: Updated ternery expression to be compatible with PHP 7.4

### LINKED ISSUE #569: PHP 7.4 Deprecated ternary operators without parentheses
On installation I'm getting the following error:
Deprecated: Unparenthesized \`a ? b : c ? d : e\` is deprecated. Use either \`(a ? b : c) ? d : e\` or \`a ? b : (c ? d : e)\` in /var/www/html/moodle38/mod/turnitintooltwo/sdk/soap.class.php on line 218

This is deprecated as of PHP7.4
https://www.php.net/manual/en/migration74.deprecated.php

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #569

### CODE REVIEW

**Comment by sharpchi** [comment]
Thanks for doing the updated pull request - I was away so wasn't able to get to it.

**Comment by dmitriim** [comment]
Hi @sharpchi Any chance you can review and potentially merge it in? Thank you!

**Comment by sharpchi** [comment]
@dmitriim It's not my project to merge anything in. My comment was in relation to my own pull request that I needed to amend, but @Peterburnett got to before me.

**Comment by CharlotteSpinks** [comment]
Thanks for the PR, we'll take a look.

**Comment by Peterburnett** [comment]
Hi all, has there been any movement on this ticket?

**Comment by golenkovm** [comment]
Hi @CharlotteSpinks 
Could you please let us know if there is a chance to fix this issue?
Thanks

**Comment by jmcgettrick** [comment]
Fixed in #590

**Pull request closed without merging**
