### PR TITLE
fixed optional parameter before required parameter issue with show_form()

### LINKED ISSUE #701: Default activity completion: Required parameter $tiicourseid follows optional parameter
There are issues with the Course Completion.

If course completion is on and you try to view "Default activity completion" for a course the following error can be seen:

Deprecated: Required parameter $tiicourseid follows optional parameter $modulestring in /var/www/html/mod/turnitintooltwo/mod_form.php on line 125

### PR DESCRIPTION
**Pull request by opitz**
This will fix #701.

### CODE REVIEW

**Comment by steveorulez** [comment]
Hello, we have the same error on moodle 4.3 php 8.2, can you apply this change?

christian

**Comment by jack-tii** [comment]
Thanks for the contribution. I am closing this as it is a duplicate of #668

**Comment by jack-tii** [comment]
Actually, reopening because this one is pointing at the develop branch

**Review by jack-tii — APPROVED** [review]
Looks good, thanks for your contribution!

**Pull request merged**
