### PR TITLE
Fix failing Behat test

### LINKED ISSUE #706: Failing core Behat tests in default_activiy completion.feature
The error message:

```
Moodle exception: Exception - Warning: Undefined property: stdClass::$apiurl in [dirroot]/mod/turnitintooltwo/turnitintooltwo_comms.class.php on line 39 More information about this error
        
Exception - Warning: Undefined property: stdClass::$apiurl in [dirroot]/mod/turnitintooltwo/turnitintooltwo_comms.class.php on line 39

```

The reason for this is that at the time of the test no apiurl has been set for the turnitintolltwo plugin configuration (there is no default value given). When then trying to read that (non-existent) configuration value the issue is triggered.

### PR DESCRIPTION
**Pull request by opitz**
Abort definition() if page output has begun.
This will fix #706.

### CODE REVIEW

**Comment by aspark21** [comment]
This is still unresolved in latest version @carl-hostrander - this isn't just about behat tests but interferes with the newly introduced bulk activity completion view introduced in 4.3

**Comment by carl-hostrander** [comment]
Thanks @aspark21 for verifying these are all issues.

**Comment by aspark21** [comment]
rebased fix on develop to make it easier to test

**Review by jack-tii — APPROVED** [review]
Happy with these changes, thanks!

**Comment by jack-tii** [comment]
Linking https://github.com/turnitin/moodle-plagiarism_turnitin/pull/692 for visibility

**Pull request merged**
