### PR TITLE
Fix deprecated ternary operator syntax for PHP 7.4

### PR DESCRIPTION
**Pull request by sharpchi**
Ref Issue #569

### CODE REVIEW

**Comment by sharpchi** [comment]
Now that ubuntu 20.04.01 is out (which ships with PHP7.4) people's error logs are going to fill with this deprecated error. It would be good to sort it. Thanks.

**Comment by borrown** [comment]
I think your solution approach is not correct. Extra parenthesis should surround the last part of the sentence, like this:

$port = ( isset( $parse["port"] ) AND ( $parse["port"] == '80' OR $parse["port"] == '443' ) )
                ? '' : (!isset( $parse["port"] ) ? '' : ':'.$parse["port"]);

**Comment by Peterburnett** [comment]
I agree, the else condition should have parentheses. @sharpchi are you able to amend this PR?

**Comment by Peterburnett** [comment]
I have made a new PR with the second expression bracketed here: #587

**Comment by sharpchi** [comment]
I'll close this PR as @Peterburnett has done an updated one.

**Pull request closed without merging**
