### PR TITLE
CCLE-7690 - Fixed close buttons for Turnitin Notify Non submitters and Messages Inbox.

### PR DESCRIPTION
**Pull request by rlorenzo**
As mentioned in https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/451

We are running 2018052301 and found more Close Button issues.

### CODE REVIEW

**Comment by dwinn** [comment]
Hi @rlorenzo ,

Would you be able to rebase this and make the pull request to develop instead of master please?

The JS files now have a version number in the file name as well which will have to be taken into consideration.

**Comment by rlorenzo** [comment]
@dwinn I updated the branch to be based off develop and edited the versioned min.js file.

**Comment by rlorenzo** [comment]
@dwinn Can this be merged in? We are updating to the newest TurnItIn plugin and would like to stop carrying over this edit manually.

**Comment by dwinn** [comment]
Hi @rlorenzo,

I will discuss with our team about when we can release this change. We have to QA the change before we can merge it. The code looks fine however.

**Comment by dwinn** [comment]
Hi @rlorenzo,

Thanks for the fix. I've merged and tested your pull request. All seems good so we'll be including it in our next release. I can't give a date for the release but it will be very soon.

**Pull request merged**
