### PR TITLE
consolidate inclusion paths under ./sdk

### PR DESCRIPTION
**Pull request by eviweb**
Signed-off-by: Eric Villard dev@eviweb.fr

### CODE REVIEW

**Comment by jmcgettrick** [comment]
Hey @eviweb, can you remake this PR to the develop branch and we'll merge it in.
Thanks

**Comment by eviweb** [comment]
Hi @jmcgettrick,
the base branch is changed.
best regards
Eric

**Comment by jmcgettrick** [comment]
Hi @eviweb, sorry I've had to remove these changes as they broke the plugin for us.

**Comment by eviweb** [comment]
Hi @jmcgettrick,
for sure, I'm sorry to hear about that.
But it seems to be strange...
Do you have any error messages ?
Which PHP version do you use ?
May you give me a reproducible use case, I can investigate ?
Thanks
Eric

**Comment by jmcgettrick** [comment]
Hi @eviweb, yes it seemed a bit strange to me. I'm running it via Docker and get:

```No such file or directory in /app/moodle/mod/turnitintooltwo/sdk/api.class.php on line 3
Fatal error: require_once(): Failed opening required '/app/moodle/mod/turnitintooltwo/sdkusersoap.class.php' (include_path='/app/moodle/lib/pear:/app/moodle/lib/pear:.:/usr/share/php:/usr/share/pear') in /app/moodle/mod/turnitintooltwo/sdk/api.class.php on line 3
PHP Warning:  require_once(/app/moodle/mod/turnitintooltwo/sdkusersoap.class.php): failed to open stream: No such file or directory in /app/moodle/mod/turnitintooltwo/sdk/api.class.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/app/moodle/mod/turnitintooltwo/sdkusersoap.class.php' (include_path='/app/moodle/lib/pear:/app/moodle/lib/pear:.:/usr/share/php:/usr/share/pear') in /app/moodle/mod/turnitintooltwo/sdk/api.class.php on line 3```

**Comment by eviweb** [comment]
Hi @jmcgettrick,
it should be fixed on my branch and was an error on my part, sorry for this.
Would you like I submit a new PR on the develop branch or do you prefer to test it first from my last commit https://github.com/eviweb/moodle-mod_turnitintooltwo/commit/a654b7e0bee5889817f29a12c2c33456cbc94c93 ?
Eric

**Comment by jmcgettrick** [comment]
It's no problem, make a PR and we'll give it another shot!

**Comment by eviweb** [comment]
Hi @jmcgettrick,
done #233

**Pull request merged**
